/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/todos": {
    get: operations["getTodos"];
    post: operations["addTodo"];
  };
  "/todos/{id}": {
    get: operations["getTodoById"];
    delete: operations["removeTodo"];
  };
}

export interface components {
  schemas: {
    Todo: {
      id: string;
      state: string;
      title: string;
      description: string;
      lastUpdate: string;
    };
    AddTodo: {
      title: string;
      description: string;
    };
  };
}

export interface operations {
  getTodos: {
    responses: {
      /** successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Todo"][];
          "text/calendar": string;
        };
      };
    };
  };
  addTodo: {
    responses: {
      /** successful operation */
      201: {
        content: {
          "application/json": components["schemas"]["Todo"];
        };
      };
      /** you are not logged in */
      401: unknown;
      /** you are not authorized to add todos */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddTodo"];
      };
    };
  };
  getTodoById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Todo"];
        };
      };
    };
  };
  removeTodo: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** successful operation */
      200: unknown;
      /** you are not logged in */
      401: unknown;
      /** you are not authorized to remove todos */
      403: unknown;
    };
  };
}
